version: "3.9"

services:
  arangodb:
    container_name: arangodb
    image: arangodb:3.8.4
    restart: always
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGO_ROOT_PASSWORD}
    volumes:
      - .data/article:/var/lib/arangodb3
