version: "3.9"

services:
  crawler:
    image: news-crawler
    container_name: news-crawler
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ARANGO_URL=tcp://arangodb:8529
      - ARANGO_ROOT_USERNAME=${ARANGO_ROOT_USERNAME}
      - ARANGO_ROOT_PASSWORD=${ARANGO_ROOT_PASSWORD}
      - ARANGO_POOL_SIZE=${ARANGO_POOL_SIZE}
      - EXAME_FREQUENCY_MINUTES=${EXAME_FREQUENCY_MINUTES}
      - INFOMONEY_FREQUENCY_MINUTES=${INFOMONEY_FREQUENCY_MINUTES}
      - TZ=America/Sao_Paulo
    networks:
      - app_net
  arangodb:
    container_name: arangodb
    image: arangodb:3.8.4
    restart: always
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGO_ROOT_PASSWORD}
    volumes:
      - .data/article:/var/lib/arangodb3
    networks:
      - app_net

networks:
  app_net:
